### ISSUE TITLE
Enabling Wayland does not display gnome theme

### ISSUE THREAD

**Issue by castagnag** [luminoso/fedora-copr-signal-desktop#7]
If I launch signal with
--enable-features=UseOzonePlatform --ozone-platform=wayland
then the gnome theme is not displayed (missing window decoration and top bar with close/minimize icons)

**Comment by luminoso** [comment]
![Screenshot from 2021-05-18 20-39-19](https://user-images.githubusercontent.com/296323/118721339-a1ed1480-b822-11eb-8525-09bf785a4256.png)

Is this the issue? I don't see any problem with the theme.

**Comment by luminoso** [comment]
![Screenshot from 2021-05-18 21-55-24](https://user-images.githubusercontent.com/296323/118722209-ce556080-b823-11eb-8329-194b061e4ddf.png)

I was able to replicate the issue.
Both with copr package but also with signal-desktop official build (screenshot above)

Since it happens in both versions I believe this is an upstream issue and not a packaging issue.

My suggestion is to report the bug directly to signal project [here](https://github.com/signalapp/Signal-Desktop) or in their forums [here](https://community.signalusers.org/)
